apiVersion: apps/v1
kind: Deployment
metadata:
  name: sms-webhook-deployment
  namespace: sms-webhook
  labels:
    app: sms-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sms-webhook
  template:
    metadata:
      labels:
        app: sms-webhook
    spec:
      containers:
      - name: sms-webhook
        image: 10.29.230.150:31381/library/sms-test:20251103
        ports:
        - containerPort: 8080
        env:
        - name: SMS_API_URL
          value: "http://kramd1.kinzhi.net:18055/post"
        - name: SMS_CODE
          value: "ALERT_CODE"
        - name: SMS_TARGET
          value: "15222222222"
        - name: PORT
          value: "8080"
        - name: LOG_LEVEL
          value: "info"
        resources:
          requests:
            memory: "200Mi"
            cpu: "200m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"

---
apiVersion: v1
kind: Service
metadata:
  name: sms-webhook-service
  namespace: sms-webhook
spec:
  type: NodePort # ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30127
  selector:
    app: sms-webhook